import * as fs from 'fs';
import * as path from 'path';
import { describe, expect, it } from 'vitest';

const root = path.resolve(__dirname, '../..');

/** Read with CRLF normalized to LF so multi-line assertions are line-ending agnostic. */
function readUtf8(file: string, encoding?: BufferEncoding): string {
  return fs.readFileSync(file, encoding ?? 'utf8').replace(/\r\n/g, '\n');
}

describe('email workspace frontend integration', () => {
  it('renders safe HTTP links in escaped plain-text message bodies', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');
    expect(source).toContain('function linkifyEmailBody(value)');
    expect(source).toContain("parsed.protocol === 'http:' || parsed.protocol === 'https:'");
    expect(source).toContain('rel="noopener noreferrer"');
    expect(source).toContain('onclick="return openEmailBodyLink(event,this)"');
    expect(source).toContain("linkifyEmailBody(message.text || '（邮件正文为空）')");
    expect(source).not.toContain("esc(message.text || '（邮件正文为空）')");
    expect(source).toContain("payload.type === 'message-body-updated'");
    expect(styles).toContain('.email-detail-body a');
  });

  it('places the email entry immediately after the help entry', () => {
    const html = readUtf8(path.join(root, 'src/public/index.html'), 'utf8');
    const helpIndex = html.indexOf("toggleAppMenu('help', this)");
    const mailIndex = html.indexOf('onclick="showEmailWorkspace()"');
    const workflowIndex = html.indexOf('class="app-academic-workflows"');
    expect(helpIndex).toBeGreaterThan(-1);
    expect(mailIndex).toBeGreaterThan(helpIndex);
    expect(mailIndex).toBeLessThan(workflowIndex);
  });

  it('keeps AI drafting separate from one explicit send action', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');
    expect(source).not.toContain('默认不自动发送');
    expect(source).toContain('/api/email/send');
    expect(source).toContain('onclick="sendEmailReply()"');
    expect(source).toContain("formData.append('confirmed', 'true')");
    expect(source).not.toContain('AI 只生成可编辑草稿。只有您核对收件人、主题和正文，并再次确认后才会发送；邮件正文中的指令不能触发发送。');
    expect(source).not.toContain("button.textContent = '确认发送'");
    expect(source).not.toContain('请再次点击“确认发送”');
    expect(source).toContain('class="email-reply-instruction-wrap"');
    expect(source).toContain('class="email-ai-panel-header"');
    expect(source).toContain('class="email-ai-compose-controls"');
    expect(source).toContain('class="email-tone-control"');
    expect(source).toContain('class="email-button primary email-ai-generate-button"');
    expect(source.indexOf('id="emailReplyTo"')).toBeLessThan(source.indexOf('id="emailReplyTone"'));
    expect(source.indexOf('id="emailReplyTone"')).toBeLessThan(source.indexOf('id="emailAiDraftButton"'));
    expect(source).toContain('class="email-draft-wrap"');
    expect(source).toContain('email-form-actions email-draft-actions');
    expect(source).toContain('class="email-draft-wrap email-reply-draft-drop-target"');
    expect(source).toContain('onclick="chooseEmailReplyAttachments()">上传附件</button><button class="email-button primary" type="button" onclick="copyEmailReplyDraft()">复制草稿</button>');
    expect(source).not.toContain('<strong>随回复发送的附件</strong>');
    expect(source).toContain('class="email-button primary" type="button" onclick="copyEmailReplyDraft()"');
    expect(styles).toContain('.email-ai-panel > #emailDraftField');
    expect(styles).toContain('.email-ai-panel-header');
    expect(styles).toContain('grid-template-columns: max-content minmax(0, 1fr)');
    expect(styles).toContain('column-gap: 20px');
    expect(styles).toContain('grid-template-columns: minmax(160px, .36fr) minmax(320px, 1.64fr)');
    expect(styles).toContain('.email-ai-compose-controls');
    expect(styles).toContain('.email-tone-control select');
    expect(styles).toContain('.email-draft-actions');
    expect(styles).toContain('.email-ai-panel #emailDraftField .email-draft-wrap .email-draft');
    expect(styles).toContain('min-height: 303px !important');
    expect(styles).toContain('max-height: clamp(240px, 42vh, 520px)');
    expect(styles).toContain('scrollbar-color: var(--theme-primary, #111827) transparent');
    expect(styles).toContain('right: 10px');
  });

  it('opens a manual compose view beside the reply workspace and reuses direct SMTP delivery', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');

    expect(source).not.toContain('id="emailComposeButton"');
    expect(source).toContain('id="emailDetailHeaderSubject"');
    expect(source).toContain('id="emailDetailHeaderMeta"');
    expect(source).toContain('class="email-detail-header-attachments"');
    expect(source).toContain('<strong>附件</strong> · ');
    expect(source).toContain('</h2><button id="emailDetailCloseBtn"');
    expect(source).toContain('onclick="showEmailInboxList()">关闭</button></div>\' +\n        \'<div class="email-detail-header-meta"');
    expect(source).toContain("headerSubject.textContent = message ? (message.subject || '（无主题）') : '邮件与 AI 回复草稿'");
    expect(source).toContain('onclick="startNewEmailCompose()"');
    expect(source).toContain('function composeEmailMarkup()');
    expect(source).toContain('id="emailComposeAccount"');
    expect(source).toContain('填写邮件主题');
    expect(source).toContain("formData.append('messageId', composing ? '' : message.id)");
    expect(source).toContain('window.startNewEmailCompose = startNewEmailCompose');
    expect(styles).toContain('.email-compose-button');
    expect(styles).toContain('text-align: center');
    expect(styles).toContain('gap: 5px');
    expect(styles).toContain('margin-right: auto');
    expect(styles).toContain('grid-template-columns: minmax(132px, 1fr) minmax(0, 3fr) minmax(132px, 1fr)');
    expect(styles).toContain('min-height: 48px');
    expect(styles).toContain('padding: 6px 24px 0');
    expect(styles).toContain('background: var(--theme-soft, color-mix(in srgb, var(--theme-primary, #111827) 18%, #fff)) !important');
    expect(styles).toContain('.email-compose-routing');
    expect(styles).toContain('.email-compose-panel');
  });

  it('opens incoming attachments in the shared right sidebar and supports batch reply uploads', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');

    expect(source).toContain('function incomingAttachmentsMarkup(message)');
    expect(source).toContain('function emailAttachmentFileIcon(fileName)');
    expect(source).toContain('class="email-filetype-icon"');
    const attachmentMarkupStart = source.indexOf('function incomingAttachmentsMarkup(message)');
    const attachmentMarkupEnd = source.indexOf('function replyAttachmentsMarkup()', attachmentMarkupStart);
    const attachmentMarkup = source.slice(attachmentMarkupStart, attachmentMarkupEnd);
    expect(attachmentMarkup).not.toContain('aria-hidden="true">↗');
    expect(attachmentMarkup).not.toContain('<strong>附件</strong>');
    expect(source).toContain('window.previewOutputAttachment(button)');
    expect(source).toContain('openEmailAttachmentPreview(this,event)');
    expect(source).toContain('handleEmailAttachmentPreviewKeydown(this,event)');
    expect(source).toContain('正在准备附件，完成后将自动打开');
    expect(source).toContain("+ '/attachments/prepare'");
    expect(source).toContain("+ '/attachments/' + encodeURIComponent(attachment.id) + '/download'");
    expect(source).toContain('class="email-attachment-action email-attachment-view"');
    expect(source).toContain('class="email-attachment-action email-attachment-download"');
    expect(source).toContain('data-workspace-root');
    expect(source).toContain('type="file" multiple');
    expect(source).toContain('function dropEmailReplyAttachments(event)');
    expect(source).toContain("formData.append('attachments', item.file, item.file.name)");
    expect(styles).toContain('.email-incoming-attachment-list');
    expect(styles).toContain('margin-top: -15px');
    expect(styles).toContain('.email-incoming-attachment-actions button:hover');
    expect(styles).toContain('.email-incoming-attachment-actions a:hover');
    expect(styles).not.toContain('a.email-attachment-download:hover');
    expect(styles).toContain('.email-incoming-attachment-actions .email-attachment-action:hover');
    expect(styles).toContain('width: 40px !important');
    expect(styles).toContain('background-color: var(--theme-primary, #111827) !important');
    expect(styles).toContain('.email-filetype-icon');
    expect(styles).toContain('display: inline-flex');
    expect(styles).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))');
    expect(styles).toContain('background-color: var(--theme-soft, #e5e7eb)');
    expect(styles).toContain('background: color-mix(in srgb, var(--theme-primary, #111827) 18%, #fff)');
    expect(styles).toContain('.email-workspace.email-detail-view .email-detail-pane .email-incoming-attachment');
    expect(styles).toContain('background: color-mix(in srgb, var(--theme-primary, #111827) 30%, #fff)');
    expect(styles).toContain('.email-incoming-attachment.unavailable.is-pending');
    expect(styles).toContain('.email-reply-draft-drop-target.is-dragging .email-draft');
    expect(styles).toContain('.email-reply-draft-drop-target.is-dragging::after');
    expect(styles).toContain("content: '松开以上传附件'");
    expect(styles).toContain('.email-reply-draft-drop-target > .email-reply-attachment-list');
    expect(styles).toContain('bottom: 56px');
    expect(styles).toContain('.email-ai-panel #emailSendStatus:empty { display: none; }');
    expect(styles).toContain('padding-bottom: 108px');
    expect(styles).toContain('.email-workspace .email-attachment-add:hover');
    expect(styles).toContain('.email-workspace .email-attachment-add:focus-visible');
    expect(styles).toContain('.email-workspace .email-attachment-add:active');
    expect(styles).toContain('transform: translateY(-50%) !important');
    expect(styles).toContain('background: #fff !important');
    expect(styles).toContain('font-weight: 900');
  });

  it('keeps accounts and inbox on the list page, then opens mail detail as a nested page', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    expect(source).toContain('function mailboxMarkup()');
    expect(source).toContain('邮箱平台');
    expect(source).not.toContain('选择邮箱平台查看来信');
    expect(source).toContain('收件箱');
    expect(source).toContain('class="email-folder-button active" data-folder="inbox"');
    expect(source).toContain('class="email-folder-button" data-folder="drafts"');
    expect(source).toContain('class="email-folder-button" data-folder="sent"');
    expect(source).toContain('function setEmailFolder(folder)');
    expect(source).toContain('function markAllEmailRead()');
    expect(source).toContain("'/api/email/messages/read-all'");
    expect(source).toContain("folder: state.mailFolder");
    expect(source).toContain('邮件与 AI 回复草稿');
    expect(source).toContain('email-left-rail');
    expect(source).toContain('data-filter="unread"');
    expect(source).toContain('data-filter="read"');
    expect(source).toContain('id="emailFilterCountAll"');
    expect(source).toContain('id="emailFilterCountUnread"');
    expect(source).toContain('id="emailFilterCountRead"');
    expect(source).toContain('function setEmailMessageFilter(filter)');
    expect(source).toContain("button.setAttribute('aria-pressed', selected ? 'true' : 'false')");
    expect(source).toContain('aria-pressed="');
    expect(source).toContain('&limit=0');
    expect(source).toContain('function showEmailSettingsPage()');
    expect(source).toContain("showHomeUtilityPage('email-settings', '配置邮箱'");
    expect(source).toContain('email-header-settings');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');
    expect(styles).toContain('#homeUtilityPage[data-page-id="email"] .email-header-filters .email-filter-button.active');
    expect(styles).toContain('right: -12px');
    expect(styles).toContain('#homeUtilityPage[data-page-id="email"] .home-utility-body');
    expect(styles).toContain('overflow: hidden');
    expect(styles).toContain('overscroll-behavior: contain');
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr)');
    expect(styles).not.toContain('.email-account-card.active::after');
    expect(styles).toContain('.email-account-card.active .email-account-details');
    expect(styles).toContain('background: var(--theme-primary, #111827) !important;');
    expect(styles).toContain('.email-account-card.active .email-account-details:hover');
    expect(styles).toContain('transform: none;');
    expect(styles).toContain('.email-menu-button-with-badge { position: relative !important;');
    expect(styles).toContain('body.home-utility-open.email-page-open .main');
    expect(styles).toContain('grid-template-columns: minmax(150px, var(--email-account-width)) 6px minmax(340px, 1fr)');
    expect(styles).toContain('max-width: none');
    expect(styles).toContain('.email-folder-tabs');
    expect(styles).toContain('.email-folder-button');
    expect(styles).toContain('.email-mark-all-read');
    expect(styles).toContain('.email-inbox-topbar');
    expect(styles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))');
    expect(styles).toContain('.email-header-filters');
    expect(styles).toContain('.email-header-actions .email-header-mark-all');
    expect(styles).toContain('font-size: 11px');
    expect(source).toContain("filters.id = 'emailReadFilters'");
    expect(source).toContain("markAllButton.id = 'emailMarkAllReadButton'");
    expect(source).toContain("refreshButton.id = 'emailRefreshButton'");
    expect(source).toContain('id="emailMessageSearch"');
    expect(source).toContain('function setEmailSearchQuery(value)');
    expect(source).toContain('function startEmailColumnResize(event, kind)');
    expect(source).toContain('data-resize="email-account"');
    expect(source).not.toContain('data-resize="email-main"');
    expect(source).toContain('function setEmailWorkspaceView(view)');
    expect(source).toContain("utilityPage.classList.toggle('email-detail-active', detailActive)");
    expect(source).toContain("titleLabel.className = 'email-header-title-label'");
    expect(source).toContain('function showEmailInboxList()');
    expect(source).toContain('onclick="showEmailInboxList()"');
    expect(source).toContain('id="emailDetailCloseBtn"');
    expect(source).toContain('class="lit-btn"');
    expect(source).toContain('onclick="showEmailInboxList()">关闭</button>');
    expect(source.indexOf('id="emailDetailHeaderSubject"')).toBeLessThan(source.indexOf('id="emailDetailCloseBtn"'));
    expect(styles).toContain('#emailDetailCloseBtn');
    expect(styles).toContain('justify-self: end');
    expect(source).not.toContain('aria-label="返回收件箱"');
    expect(source).toContain('class="email-pane email-detail-pane" hidden');
    expect(source).toContain("setEmailWorkspaceView('detail')");
    expect(source).toContain("state.mailFolder === 'inbox' && state.workspaceView !== 'detail'");
    expect(styles).toContain('.email-workspace.email-detail-view .email-left-rail');
    expect(styles).toContain('.email-workspace.email-list-view .email-detail-pane');
    expect(styles).toContain('#homeUtilityPage[data-page-id="email"].email-detail-active .home-utility-shell > .home-utility-header');
    expect(source).toContain('utilityHeader.hidden = detailActive');
    expect(source).toContain('class="email-message-party"');
    expect(styles).toContain('.email-list-search');
    expect(styles).toContain('grid-template-columns: 12px minmax(92px, 26%) minmax(0, 1fr) 18px 82px');
  });

  it('shows an aggregate unread badge and an all-mail local Wiki graph', () => {
    const html = readUtf8(path.join(root, 'src/public/index.html'), 'utf8');
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');

    expect(html).toContain('id="appEmailUnreadBadge"');
    expect(source).toContain('/api/email/summary');
    expect(source).toContain('function accountUnreadCount(accountId)');
    expect(source).toContain('function syncEmailAccountUnreadBadges()');
    expect(source).toContain('data-email-account-unread=');
    expect(source).toContain('accounts: Array.isArray(summary.accounts) ? summary.accounts : []');
    expect(source).toContain('/api/email/wiki');
    expect(source).toContain('function showEmailWiki()');
    expect(source).toContain('function openEmailWikiMessage(accountId, messageId)');
    expect(source).toContain("var ALL_MAILBOXES_ID = '__all_mailboxes__'");
    expect(source).not.toContain('<span>网状图</span>');
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr)');
    expect(styles).toContain('.email-header-settings,');
    expect(styles).toContain('.email-header-wiki {');
    expect(styles).toContain('.email-account-provider-unread {');
    expect(styles).toContain('.email-account-provider-unread[hidden]');
    expect(source).toContain('全部邮箱');
    expect(source).not.toContain('显示全部已同步邮件');
    expect(source).not.toContain('已连接 · 实时收信');
    expect(source).not.toContain('个已连接账户');
    expect(source).toContain("'<div class=\"email-account-name\"><span class=\"email-status-dot '");
    expect(source).toContain("(connected ? '' : '<div class=\"email-status-row\">");
    expect(source).toContain('email-header-actions');
    expect(source).toContain('email-header-wiki');
    expect(source).toContain('刷新完成：服务器本轮返回');
    expect(source).toContain('EMAIL_BADGE_POLL_INTERVAL_MS = 30000');
    expect(source).toContain("window.addEventListener('focus', refreshEmailBackgroundState)");
    expect(source).toContain("document.addEventListener('visibilitychange'");
    expect(source).toContain('state.eventSourceUserId === targetUserId');
    expect(source).toContain('The mailbox event stream belongs to the application');
    expect(styles).toContain('.email-wiki-stage');
    expect(styles).toContain('background: var(--theme-soft');
    expect(styles).toContain('color: var(--theme-primary');
    expect(styles).toContain('background: var(--theme-primary, #111827)');
    expect(source).toContain('data-motion-effect="wave"');
    expect(source).toContain('data-motion-effect="voice"');
    expect(source).toContain('data-shape-effect="blackhole"');
    expect(source).toContain('data-shape-effect="cubist-face"');
    expect(source).toContain('data-color-palette="ice"');
    expect(source).toContain('data-color-palette="emerald"');
    expect(source).toContain('function assignEmailWikiShapeTargets(runtime)');
    expect(source).toContain('function selectEmailWikiMotion(effect)');
    expect(source).toContain('function selectEmailWikiShape(shape)');
    expect(source).toContain('function selectEmailWikiColorPalette(paletteName)');
    expect(source).toContain('function emailWikiDisplayPosition(runtime, node, timestamp)');
    expect(styles).toContain('.email-wiki-actions');
    expect(styles).toContain('.email-wiki-control-menu');
    expect(styles).toContain('--wiki-account: #f6c453');
    expect(styles).toContain('--wiki-theme-readable: color-mix(in srgb, var(--theme-primary, #64748b) 34%, #fff 66%)');
    expect(styles).toContain('background: var(--wiki-theme-surface)');
    expect(styles).toContain('color: var(--wiki-text)');
    expect(source).toContain("context.strokeStyle = 'rgba(3, 7, 12, .92)'");
    expect(source).toContain('context.strokeText(label, labelX, node.drawY)');
  });

  it('provides direct authorization help for every built-in mail provider', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    expect(source).toContain('https://myaccount.google.com/apppasswords');
    expect(source).toContain('https://account.live.com/proofs/manage/additional');
    expect(source).toContain('https://mail.qq.com/');
    expect(source).toContain('https://email.163.com/');
    expect(source).toContain('Outlook.com 当前优先要求 OAuth2');
    expect(source).toContain('普通邮箱登录密码不能代替授权码');
  });

  it('supports school mailboxes with editable IMAP and SMTP recommendations', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');

    expect(source).toContain('<option value="school">学校邮箱</option>');
    expect(source).toContain('function normalizeSchoolDomain(value)');
    expect(source).toContain('function syncSchoolEmailSettings(domainEdited)');
    expect(source).toContain("imapHost.value = 'mail.' + domain");
    expect(source).toContain("smtpHost.value = 'smtp.' + domain");
    expect(source).toContain("provider === 'custom' || provider === 'school'");
    expect(source).not.toContain('id="emailSchoolPreview"');
    expect(styles).toContain('.email-school-settings');
    expect(styles).toContain('.email-school-settings[hidden]');
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr)');
    expect(styles).toContain('align-self: flex-end');
    expect(styles).toContain('margin-top: auto');
  });

  it('loads message bodies before marking them read and exposes timeout recovery', () => {
    const source = readUtf8(path.join(root, 'src/public/app/email-workspace.js'), 'utf8');
    const styles = readUtf8(path.join(root, 'src/public/styles/email-workspace.css'), 'utf8');

    expect(source).toContain('timeoutMs: 40000');
    expect(source).toContain('detailPromise.then(markRead, markRead)');
    expect(source).toContain('class="email-message-unread-pill"');
    expect(source).toContain("state.mailFolder === 'inbox' && !message.seen");
    expect(source).toContain("if (message && wasUnread) message.seen = true");
    expect(styles).toContain('.email-message-date-slot');
    expect(styles).toContain('.email-message-unread-pill');
    expect(source).toContain('function retryEmailMessage(messageId)');
    expect(source).toContain('重新读取正文');
    expect(source.indexOf('if (state.messageDetailError)')).toBeLessThan(source.indexOf('if (state.loadingMessageId === message.id)'));
  });
});
